### ISSUE TITLE
Save/Load RAM state with button "1" and "2" on keyboard

### ISSUE THREAD

**Issue by SkycoinSynth** [skycoin/cx-aigym-nes#2]
Button "1" on keyboard to save RAM state (2 KB byte array)
- to a save slot or variable in manager

Button "2" to load RAM state (if there is a previously saved state)
- to load the ram state from the save slot or variable in manager

Verify that save/load works for RAM.

**Comment by andrewvo148** [comment]
```
func (view *GameView) saveState() {
	view.state = view.console.SaveStateToBytes()
}

func (view *GameView) loadState() {
	if view.state != nil {
		view.console.LoadStateFromBytes(view.state)
	}
}
```

**Comment by andrewvo148** [comment]
Ctrl + A: Save State
Ctrl + B: Load State
