### ISSUE TITLE
Button "5" to save game state to file

### ISSUE THREAD

**Issue by SkycoinSynth** [skycoin/cx-aigym-nes#4]
1> When Button "5" on keyboard is pressed
- get unix time as int32
- save the current ram state as "[int unix time].ram"

2> Save file [int unix time].json
- have fields
- uint32 unit time as integer as string (same as above)
- ROM filename
- ROM sha256 hash
- game frame int (doesnt matter if not recorded yet). Use zero for now
- SHA256 hash of the RAM state at this point
- screenshot file name (see #2)
- .ram file name (see #1)

3> Save screenshot of game as .png at this point
- as "[int32 unix time].png"

4> Save these three files to "checkpoints" folder in root directory.

5> Option on command line to load the .json file and start game from that point.
- looks for ROM file name in ROMs folder
- looks for .ram file in the checkpoints folder
- loads rom
- loads ram state
- starts game

**Comment by andrewvo148** [comment]
1.
```
func (view *GameView) saveStateToFiles(now int64) error {
	path := fmt.Sprintf("%s/%d.ram", PATH_CHECKPOINTS, now)
	return view.console.SaveState(path)
}
```
2.
```
func (view *GameView) saveToJson(now int64) error {
	view.StateHash = fmt.Sprintf("%x", sha256.Sum256(view.state))
	file, err := json.MarshalIndent(view, "", " ")
	if err != nil {
		return err
	}

	path := fmt.Sprintf("%s/%d.json", PATH_CHECKPOINTS, now)
	return ioutil.WriteFile(path, file, 0644)
}
```
3.
```
func (view *GameView) saveScreenshot(now int64) error {
	path := fmt.Sprintf("%s/%d.png", PATH_CHECKPOINTS, now)
	return savePNG(path, view.console.Buffer())
}
```
